dist: trusty
language: java
sudo: false
install: true

jdk: 
  - openjdk7
  - openjdk8
  - openjdk11

script:
  - mvn clean verify -B -e -V

cache:
  directories:
    - '$HOME/.m2/repository'

branches:
    except:
        - gh-pages

notifications:
  email: true
