dist: xenial
language: java
install: true

os:
  - linux

jdk: 
  - openjdk7
  - openjdk8
  - openjdk11

env:
  global:
    - MVN_VERSION="3.6.3"

script:
  - mvn -version
  - mvn clean verify -B -e -V

cache:
  directories:
    - '$HOME/.m2/repository'

branches:
    except:
        - gh-pages

notifications:
  email: true
